#!/usr/bin/env python3
#
# shaders.py - QPU fragment shaders for the bare-metal V3D demo
#
# Generates shaders.h (run by the Makefile). Both shaders are single-threaded.
#
import math
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'devtools'))
from qpuasm import Program


def fragment_end(p, color):
    """Write Z and colour to the tile buffer and end the thread."""
    p.sig('sbwait')
    p.mov('tlbz', 'rb15')		# interpolated Z (fragment payload)
    p.mov('tlbc', color)
    p.sig('thrend')
    p.sig('nop')
    p.sig('sbdone')


def cube_shader():
    """Perspective-correct interpolation of 3 colour varyings."""
    p = Program('CubeShader')
    for i, acc in enumerate(('r0', 'r1', 'r2')):
        p.fmul(acc, 'vary', 'ra15')	# varying * W ...
        p.fadd(acc, acc, 'r5')		# ... + C
    # R in byte 0: verified on the panel for both the 8888 and the 565 store
    p.mov('r3.8a', 'r0')
    p.mov('r3.8b', 'r1')
    p.mov('r3.8c', 'r2')
    p.mov('r3.8d', 1.0)
    fragment_end(p, 'r3')
    return p


# sin (2 pi s), s in [-0.5, 0.5): odd Taylor polynomial of degree 9 (as Mesa vc4)
TWO_PI = 2.0 * math.pi
SIN_COEFFS = [TWO_PI, -TWO_PI ** 3 / 6, TWO_PI ** 5 / 120, -TWO_PI ** 7 / 5040, TWO_PI ** 9 / 362880]


class SinChain:
    """Registers of one sine evaluation: X (rb), s (ra), S2 (ra), P reuses X."""
    def __init__(self, x, s, s2):
        self.x, self.s, self.s2 = x, s, s2


def sin_turns(p, c):
    """c.x holds a' = a + 512.5 (turns, positive). Result sin (2 pi a) in c.x (P)."""
    x, s, s2 = c.x, c.s, c.s2
    p.ftoi(s, x)				# i = trunc (a')
    p.itof(s, s)
    p.fsub(s, x, s)			# f = a' - i        in [0, 1)
    p.fsub(s, s, 0.5)			# s = f - 0.5       in [-0.5, 0.5)
    p.fmul(s2, s, s)
    p.fmul(x, s2, 'rb20')		# C9
    p.fadd(x, x, 'ra23')		# + C7
    p.fmul(x, x, s2)
    p.fadd(x, x, 'ra22')		# + C5
    p.fmul(x, x, s2)
    p.fadd(x, x, 'ra21')		# + C3
    p.fmul(x, x, s2)
    p.fadd(x, x, 'ra20')		# + C1
    p.fmul(x, x, s)			# * s


def plasma_shader():
    """
    v = sin (px + t) + sin (1.3 py + 0.7 t) + sin (0.8 (px + py) + 1.3 t) + sin (1.5 |p| - t)
    rgb = 0.55 * (0.5 + 0.5 cos (vec3 (0, 2.1, 4.2) + 1.2 v))

    All arguments are pre-scaled to turns (1/2pi) by the uniforms, so
    q = p / 2pi and each sine is sin (2 pi a).
    """
    p = Program('PlasmaShader')

    # constants: C1, C3, C5, C7 in regfile A, C9 in B; 0.275 and 1.0 in A
    p.ldi('ra20', SIN_COEFFS[0])
    p.ldi('ra21', SIN_COEFFS[1])
    p.ldi('ra22', SIN_COEFFS[2])
    p.ldi('ra23', SIN_COEFFS[3])
    p.ldi('rb20', SIN_COEFFS[4])
    p.ldi('ra24', 0.275)
    p.ldi('ra19', 1.0)

    # q = pixel * scale + offset (in turns)
    p.itof('r0', 'x_coord')
    p.itof('r1', 'y_coord')
    p.fmul('r0', 'r0', p.unif('ax'))
    p.fmul('r1', 'r1', p.unif('ay'))
    p.fadd('ra0', 'r0', p.unif('bx'))		# qx
    p.fadd('rb0', 'r1', p.unif('by'))		# qy

    # |q|
    p.fmul('r0', 'ra0', 'ra0')
    p.fmul('r1', 'rb0', 'rb0')
    p.fadd('r0', 'r0', 'r1')
    p.mov('sfu_rsqrt', 'r0')
    p.fmul('ra1', 'r0', 'r4')			# |q| = q2 * rsqrt (q2)

    chains = [SinChain('rb%d' % (2 + k), 'ra%d' % (3 + k), 'ra%d' % (25 + k)) for k in range(7)]

    # arguments of the four plasma sines (a' = a + 512.5)
    c = chains
    p.fadd(c[0].x, 'ra0', p.unif('t1'))		# qx + T1
    p.fmul(c[1].x, 'rb0', p.unif('k13'))		# 1.3 qy
    p.fadd(c[1].x, c[1].x, p.unif('t2'))		# + T2
    p.fadd('r2', 'ra0', 'rb0')			# qx + qy
    p.fmul(c[2].x, 'r2', p.unif('k08'))		# * 0.8
    p.fadd(c[2].x, c[2].x, p.unif('t3'))		# + T3
    p.fmul(c[3].x, 'ra1', p.unif('k15'))		# 1.5 |q|
    p.fadd(c[3].x, c[3].x, p.unif('t4'))		# + T4

    for k in range(4):
        sin_turns(p, c[k])

    # v = sum; results are in rb (P)
    p.mov('r0', c[0].x)
    p.fadd('r0', 'r0', c[1].x)
    p.fadd('r0', 'r0', c[2].x)
    p.fadd('r0', 'r0', c[3].x)			# v

    # colour: cos (K + 1.2 v) = sin in turns: v * M + D (D includes 0.25 + 512.5)
    for k, ch in enumerate(('d0', 'd1', 'd2')):
        x = c[4 + k].x
        p.fmul(x, 'r0', p.unif('m%d' % k))
        p.fadd(x, x, p.unif(ch))
    for k in range(3):
        sin_turns(p, c[4 + k])

    # rgb = 0.275 * (1 + S)
    for k, byte in enumerate(('8a', '8b', '8c')):	# R, G, B -> bytes 0, 1, 2
        p.fadd('r1', c[4 + k].x, 'ra19')
        p.fmul('r3.' + byte, 'r1', 'ra24')
    p.mov('r3.8d', 1.0)

    fragment_end(p, 'r3')
    return p


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else 'shaders.h'
    text = ['// generated by shaders.py - do not edit', '#ifndef _shaders_h', '#define _shaders_h', '',
            '#include <circle/types.h>', '']
    for prog in (cube_shader(), plasma_shader()):
        text.append(prog.c_source())
    text.append('#endif')
    open(out, 'w').write('\n'.join(text) + '\n')


if __name__ == '__main__':
    main()
