#!/usr/bin/env python3
"""The scenes' data, taken from a JetExamples checkout: its headers' arrays
(bitmaps, textures, meshes) as they are, and for each bitmap what the
original's texture said of it (its size, its colour key), as a kit::Image.
What else those headers hold (Jet's objects and the code that uses them) is
left behind: the scenes here are written again (kit.hpp).

usage: import_assets.py JETEXAMPLES OUT_DIR
  writes OUT_DIR/NAME.hpp for each header listed below
"""
import os, re, sys

HEADERS = [	# scene, upstream header, the namespace here
    ('template-cube', None, None),
    ('textured-boxes', 'Labels.hpp', 'boxes_labels'), ('textured-boxes', 'CrateTexture.hpp', 'crate'),
    ('lighting-teapot', 'Labels.hpp', 'teapot_labels'), ('lighting-teapot', 'TeapotMesh.hpp', 'teapot'),
    ('depth-teapot', 'Labels.hpp', 'depth_labels'),
    ('postfx-cel', 'Labels.hpp', 'cel_labels'),
    ('texture-features', 'Labels.hpp', 'texlab_labels'), ('texture-features', 'Assets.hpp', 'texlab'),
    ('postfx-crt', 'Labels.hpp', 'crt_labels'), ('postfx-crt', 'Assets.hpp', 'crt'),
    ('particles', 'Labels.hpp', 'particles_labels'),
    ('lod-billboards', 'Labels.hpp', 'woodland_labels'), ('lod-billboards', 'Assets.hpp', 'woodland'),
    ('lod-billboards', 'TreeData.hpp', 'woodland_trees'),
    ('sprite-controls', 'Labels.hpp', 'airmail_labels'), ('sprite-controls', 'Assets.hpp', 'airmail'),
    ('tropical-island', 'Labels.hpp', 'island_labels'),
    ('sprites-blending', 'Labels.hpp', 'courtyard_labels'), ('sprites-blending', 'Assets.hpp', 'courtyard'),
    ('neon-car', 'Labels.hpp', 'car_labels'), ('neon-car', 'Assets.hpp', 'car'),
    ('matter', 'Typography.hpp', 'matter_type'),
    ('neon-film', 'Assets.hpp', 'film'), ('neon-film', 'CreditMask.hpp', 'film_credits'),
]

ARRAY = re.compile(r'^(?:static |inline |constexpr |const |alignas\(\d+\) )+((?:unsigned )?\w+)\s+(\w+)((?:\[[^\]]*\])+)\s*=\s*\{', re.M)
TEXTURE = re.compile(r'Renderer::Texture\s+(\w+)\s*\(\s*(\w+)\s*,\s*(\w+)\s*,\s*const_cast<uint16_t\*>\((\w+)\)\s*(?:,\s*(true|false)\s*(?:,\s*(\w+))?)?')
CONSTANT = re.compile(r'^(?:inline |static )?constexpr\s+(?:int|unsigned|float|uint16_t|int16_t)\s+[^;{]*;\s*$', re.M)

def convert(text, namespace, source):
    out = ['// %s - generated by tools/import_assets.py from JetExamples %s: its data as it is' % (namespace + '.hpp', source),
           '// (MIT, CubeCoders; what the data themselves are, and whose, their header says).',
           '#pragma once', '#include <cstdint>', '#include "kit.hpp"', 'namespace %s {' % namespace]
    for m in re.finditer(r'^//.*$', text[:2000], re.M):	# its notes on where the data come from
        if re.search(r'CC0|CC-BY|licen|Generated|generated|SHA256|http', m.group(0)):
            out.append(m.group(0))
    for m in CONSTANT.finditer(text):
        out.append(m.group(0).strip())
    for m in re.finditer(r'^struct \w+ \{[^}]*\};', text, re.M):	# a data record's layout
        out.append(m.group(0))
    arrays = set()
    for m in ARRAY.finditer(text):
        depth, i = 1, m.end()
        while depth:						# to the brace that closes it
            c = text[i]
            depth += (c == '{') - (c == '}')
            i += 1
        body = text[m.end():i - 1]
        out.append('inline const %s %s%s = {%s};' % (m.group(1), m.group(2), m.group(3), body))
        arrays.add(m.group(2))
    for m in TEXTURE.finditer(text):
        name, w, h, pixels, keyed, key = m.groups()
        if pixels in arrays:
            out.append('inline const kit::Image %s = {%s, %s, %s, %s, %s};' % (
                re.sub(r'Texture$', '', name) or name, w, h, pixels, keyed or 'false', key or '0'))
    out.append('}')
    return '\n'.join(out) + '\n'

def convert_obj(text, namespace, source):
    """A model given as OBJ and MTL text: what Jet's loader (its ObjLoader.h) makes of it: a vertex for
    each v/vt/vn in use, positions doubled and cut to whole units, texture coordinates and normals in
    1024ths; the triangles of each material together, the materials in the MTL's order"""
    import numpy as np
    f32 = np.float32
    obj = re.search(r'inline const char obj\[\]\s*=\s*R"JETASSET\((.*?)\)JETASSET"', text, re.S).group(1)
    mtl = re.search(r'inline const char mtl\[\]\s*=\s*R"JETASSET\((.*?)\)JETASSET"', text, re.S).group(1)
    names = [l.split()[1] for l in mtl.splitlines() if l.startswith('newmtl')]
    v, vt, vn, lookup, vertices, triangles, current = [], [], [], {}, [], {n: [] for n in names}, None
    for l in obj.splitlines():
        w = l.split()
        if not w:
            continue
        if w[0] == 'v': v.append([f32(x) for x in w[1:4]])
        elif w[0] == 'vt': vt.append([f32(x) for x in w[1:3]])
        elif w[0] == 'vn': vn.append([f32(x) for x in w[1:4]])
        elif w[0] == 'usemtl': current = w[1]
        elif w[0] == 'f':
            face = []
            for corner in w[1:5]:
                key = tuple(int(i) for i in corner.split('/'))
                if key not in lookup:
                    lookup[key] = len(vertices)
                    p, t, n = v[key[0] - 1], vt[key[1] - 1], vn[key[2] - 1]
                    vertices.append([int(c * f32(2)) for c in p] + [int(c * f32(1024)) for c in n] + [int(c * f32(1024)) for c in t])
                face.append(lookup[key])
            triangles[current].append(face[:3])
            if len(face) == 4:
                triangles[current].append([face[0], face[2], face[3]])
    out = ['// %s - generated by tools/import_assets.py from JetExamples %s: its model (OBJ and MTL text there)' % (namespace + '.hpp', source),
           '// as Jet\'s loader reads it. (MIT, CubeCoders; what the model is, and whose, its header says.)',
           '#pragma once', '#include <cstdint>', 'namespace %s {' % namespace]
    for m in re.finditer(r'^//.*$', text[:3000], re.M):
        if re.search(r'CC0|CC-BY|licen|Generated|generated|SHA256|http', m.group(0)):
            out.append(m.group(0))
    out.append('struct Vertex { int16_t x, y, z, nx, ny, nz, u, v; };')
    out.append('struct Part { const char* material; uint16_t first, count; };	// triangles')
    out.append('inline const Vertex vertices[] = {')
    out += ['{%s},' % ','.join(str(c) for c in vertex) for vertex in vertices]
    out.append('};')
    out.append('inline const uint16_t triangles[][3] = {')
    parts, first = [], 0
    for name in names:
        out += ['{%d,%d,%d},' % tuple(t) for t in triangles[name]]
        parts.append('{"%s", %d, %d},' % (name, first, len(triangles[name])))
        first += len(triangles[name])
    out.append('};')
    out.append('inline const Part parts[] = {')
    out += parts
    out += ['};', '}']
    return '\n'.join(out) + '\n'

MODELS = [('neon-car', 'Assets.hpp', 'car_model')]

if len(sys.argv) != 3:
    sys.exit(__doc__)
root, out_dir = sys.argv[1:]
os.makedirs(out_dir, exist_ok=True)
for scene, header, namespace in HEADERS:
    if not header:
        continue
    path = os.path.join(root, 'esp32-' + scene, 'main', header)
    text = open(path).read()
    # (data given twice, for a larger render scale and for the screen's own: the latter)
    text = re.sub(r'^#if \w+_RENDER_SCALE == \d+\n.*?^#else\n(.*?)^#endif\n', r'\1', text, flags=re.S | re.M)
    result = convert(text, namespace, 'esp32-%s/main/%s' % (scene, header))
    open(os.path.join(out_dir, namespace + '.hpp'), 'w').write(result)
    print('%-24s %7d bytes, %d arrays, %d images' % (namespace + '.hpp', len(result), result.count('inline const') - result.count('kit::Image'), result.count('kit::Image')))
for scene, header, namespace in MODELS:
    text = open(os.path.join(root, 'esp32-' + scene, 'main', header)).read()
    result = convert_obj(text, namespace, 'esp32-%s/main/%s' % (scene, header))
    open(os.path.join(out_dir, namespace + '.hpp'), 'w').write(result)
    print('%-24s %7d bytes, a model' % (namespace + '.hpp', len(result)))
